In [1]:
import warnings
warnings.simplefilter('ignore')

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import numpy as np
import pandas as pd

In [4]:
pip install  matplotlib

Requirement already satisfied: matplotlib in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from matplotlib) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: numpy>=1.23 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from matplotlib) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from matplotlib) (6.4.5)
Requirement already satisfied: zipp>=3.1.0 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from importlib-resources>=3.2.0->matplotlib) (3.17.0)
Requirement already satisfied: six>=1.5 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import matplotlib.pyplot as pt

In [6]:
%matplotlib inline

In [7]:
df=pd.read_csv("C:\\Users\\aedur\\Downloads\\Admission_Predict (2).csv")

In [8]:
df

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,Yes,0.92
1,2,324,107,4,4.0,4.5,8.87,Yes,0.76
2,3,316,104,3,3.0,3.5,8.00,Yes,0.72
3,4,322,110,3,3.5,2.5,8.67,Yes,0.80
4,5,314,103,2,2.0,3.0,8.21,No,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,Yes,0.82
396,397,325,107,3,3.0,3.5,9.11,Yes,0.84
397,398,330,116,4,5.0,4.5,9.45,Yes,0.91
398,399,312,103,3,3.5,4.0,8.78,No,0.67
399,400,333,117,4,5.0,4.0,9.66,Yes,0.95

In [9]:
df2=df.drop("Serial No.",axis=1)

In [10]:
df2

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,337,118,4,4.5,4.5,9.65,Yes,0.92
1,324,107,4,4.0,4.5,8.87,Yes,0.76
2,316,104,3,3.0,3.5,8.00,Yes,0.72
3,322,110,3,3.5,2.5,8.67,Yes,0.80
4,314,103,2,2.0,3.0,8.21,No,0.65
...,...,...,...,...,...,...,...,...
395,324,110,3,3.5,3.5,9.04,Yes,0.82
396,325,107,3,3.0,3.5,9.11,Yes,0.84
397,330,116,4,5.0,4.5,9.45,Yes,0.91
398,312,103,3,3.5,4.0,8.78,No,0.67
399,333,117,4,5.0,4.0,9.66,Yes,0.95

In [11]:
df2=df.drop(["Serial No.","GRE Score","TOEFL Score","University Rating","SOP","LOR ","Research"],axis=1)

In [12]:
df2

     CGPA  Chance of Admit
0    9.65              0.92
1    8.87              0.76
2    8.00              0.72
3    8.67              0.80
4    8.21              0.65
..    ...               ...
395  9.04              0.82
396  9.11              0.84
397  9.45              0.91
398  8.78              0.67
399  9.66              0.95

[400 rows x 2 columns]

In [15]:
x=df2.iloc[:,0].values.reshape(-1,1)
y=df2.iloc[:,1].values.reshape(-1,1)

In [16]:
x

array([[9.65],
       [8.87],
       [8.  ],
       [8.67],
       [8.21],
       [9.34],
       [8.2 ],
       [7.9 ],
       [8.  ],
       [8.6 ],
       [8.4 ],
       [9.  ],
       [9.1 ],
       [8.  ],
       [8.2 ],
       [8.3 ],
       [8.7 ],
       [8.  ],
       [8.8 ],
       [8.5 ],
       [7.9 ],
       [8.4 ],
       [9.5 ],
       [9.7 ],
       [9.8 ],
       [9.6 ],
       [8.8 ],
       [7.5 ],
       [7.2 ],
       [7.3 ],
       [8.1 ],
       [8.3 ],
       [9.4 ],
       [9.6 ],
       [9.8 ],
       [9.2 ],
       [8.4 ],
       [7.8 ],
       [7.5 ],
       [7.7 ],
       [8.  ],
       [8.2 ],
       [8.5 ],
       [9.1 ],
       [9.4 ],
       [9.1 ],
       [9.3 ],
       [9.7 ],
       [8.85],
       [8.4 ],
       [8.3 ],
       [7.9 ],
       [8.  ],
       [8.1 ],
       [8.  ],
       [7.7 ],
       [7.4 ],
       [7.6 ],
       [6.8 ],
       [8.3 ],
       [8.1 ],
       [8.2 ],
       [8.2 ],
       [8.5 ],
       [8.7 ],
       [8.92],
       [9.02],
       [8.64],
       [9.22],
       [9.16],
       [9.64],
       [9.76],
       [9.45],
       [9.04],
       [8.9 ],
       [8.56],
       [8.72],
       [8.22],
       [7.54],
       [7.36],
       [8.02],
       [9.5 ],
       [9.22],
       [9.36],
       [9.45],
       [8.66],
       [8.42],
       [8.28],
       [8.14],
       [8.76],
       [7.92],
       [7.66],
       [8.03],
       [7.88],
       [7.66],
       [7.84],
       [8.  ],
       [8.96],
       [9.24],
       [8.88],
       [8.46],
       [8.12],
       [8.25],
       [8.47],
       [9.05],
       [8.78],
       [9.18],
       [9.46],
       [9.38],
       [8.64],
       [8.48],
       [8.68],
       [8.34],
       [8.56],
       [8.45],
       [9.04],
       [8.62],
       [7.46],
       [7.28],
       [8.84],
       [9.56],
       [9.48],
       [8.36],
       [8.22],
       [8.47],
       [8.66],
       [9.32],
       [8.71],
       [9.1 ],
       [9.35],
       [9.76],
       [8.65],
       [8.56],
       [8.78],
       [9.28],
       [8.77],
       [8.45],
       [8.16],
       [9.08],
       [9.12],
       [9.15],
       [9.36],
       [9.44],
       [9.92],
       [8.96],
       [8.64],
       [8.48],
       [9.11],
       [9.8 ],
       [8.26],
       [9.43],
       [9.28],
       [9.06],
       [8.75],
       [8.89],
       [8.69],
       [8.34],
       [8.26],
       [8.14],
       [7.9 ],
       [7.86],
       [7.46],
       [8.5 ],
       [8.56],
       [9.01],
       [8.97],
       [8.33],
       [8.27],
       [7.8 ],
       [7.98],
       [8.04],
       [9.07],
       [9.13],
       [9.23],
       [8.97],
       [8.87],
       [9.16],
       [9.04],
       [8.12],
       [8.27],
       [8.16],
       [8.42],
       [7.88],
       [8.8 ],
       [8.32],
       [9.11],
       [8.68],
       [9.44],
       [9.36],
       [9.08],
       [9.16],
       [8.98],
       [8.94],
       [9.53],
       [8.76],
       [8.52],
       [8.26],
       [8.33],
       [8.43],
       [8.69],
       [8.54],
       [8.46],
       [9.91],
       [9.87],
       [8.54],
       [7.65],
       [7.89],
       [8.02],
       [8.16],
       [8.12],
       [9.06],
       [9.14],
       [9.66],
       [9.78],
       [9.42],
       [9.36],
       [9.26],
       [9.13],
       [8.97],
       [8.42],
       [8.75],
       [8.56],
       [8.79],
       [8.45],
       [8.23],
       [8.03],
       [8.45],
       [8.53],
       [8.67],
       [9.01],
       [8.65],
       [8.33],
       [8.27],
       [8.07],
       [9.31],
       [9.23],
       [9.17],
       [9.19],
       [8.37],
       [7.89],
       [7.68],
       [8.15],
       [8.76],
       [9.04],
       [8.56],
       [9.02],
       [8.73],
       [8.48],
       [8.87],
       [8.83],
       [8.57],
       [9.  ],
       [8.54],
       [9.68],
       [9.12],
       [8.37],
       [8.56],
       [8.64],
       [8.76],
       [9.34],
       [9.13],
       [8.09],
       [8.36],
       [8.79],
       [8.76],
       [8.68],
       [8.45],
       [8.17],
       [9.14],
       [8.34],
       [8.22],
       [7.86],
       [7.64],
       [8.01],
       [7.95],
       [8.96],
       [9.45],
       [8.62],
       [8.49],
       [8.73],
       [8.64],
       [9.11],
       [8.79],
       [8.9 ],
       [9.66],
       [9.26],
       [9.19],
       [9.08],
       [9.02],
       [9.  ],
       [7.65],
       [7.87],
       [7.97],
       [8.18],
       [8.32],
       [8.57],
       [8.67],
       [9.11],
       [9.24],
       [8.65],
       [8.  ],
       [8.76],
       [8.45],
       [8.55],
       [8.43],
       [8.8 ],
       [9.1 ],
       [9.  ],
       [8.53],
       [8.6 ],
       [8.74],
       [9.18],
       [9.  ],
       [8.04],
       [8.13],
       [8.07],
       [7.86],
       [8.01],
       [8.8 ],
       [8.69],
       [8.5 ],
       [8.44],
       [8.27],
       [8.18],
       [8.33],
       [9.14],
       [8.02],
       [7.86],
       [8.77],
       [7.89],
       [8.66],
       [8.12],
       [8.21],
       [8.54],
       [8.65],
       [9.11],
       [8.79],
       [9.47],
       [8.74],
       [8.66],
       [8.46],
       [8.76],
       [8.24],
       [8.13],
       [7.34],
       [7.43],
       [7.64],
       [7.34],
       [7.25],
       [8.04],
       [8.27],
       [8.67],
       [8.06],
       [8.17],
       [7.67],
       [8.12],
       [8.77],
       [7.89],
       [7.64],
       [8.44],
       [8.64],
       [9.54],
       [9.23],
       [8.36],
       [8.9 ],
       [9.17],
       [8.34],
       [7.46],
       [7.88],
       [8.03],
       [8.24],
       [9.22],
       [9.62],
       [8.54],
       [7.65],
       [7.66],
       [7.43],
       [7.56],
       [7.65],
       [8.43],
       [8.84],
       [8.67],
       [9.15],
       [8.26],
       [9.74],
       [9.82],
       [7.96],
       [8.1 ],
       [7.8 ],
       [8.44],
       [8.24],
       [8.65],
       [9.12],
       [8.76],
       [9.23],
       [9.04],
       [9.11],
       [9.45],
       [8.78],
       [9.66]])

In [17]:
y

array([[0.92],
       [0.76],
       [0.72],
       [0.8 ],
       [0.65],
       [0.9 ],
       [0.75],
       [0.68],
       [0.5 ],
       [0.45],
       [0.52],
       [0.84],
       [0.78],
       [0.62],
       [0.61],
       [0.54],
       [0.66],
       [0.65],
       [0.63],
       [0.62],
       [0.64],
       [0.7 ],
       [0.94],
       [0.95],
       [0.97],
       [0.94],
       [0.76],
       [0.44],
       [0.46],
       [0.54],
       [0.65],
       [0.74],
       [0.91],
       [0.9 ],
       [0.94],
       [0.88],
       [0.64],
       [0.58],
       [0.52],
       [0.48],
       [0.46],
       [0.49],
       [0.53],
       [0.87],
       [0.91],
       [0.88],
       [0.86],
       [0.89],
       [0.82],
       [0.78],
       [0.76],
       [0.56],
       [0.78],
       [0.72],
       [0.7 ],
       [0.64],
       [0.64],
       [0.46],
       [0.36],
       [0.42],
       [0.48],
       [0.47],
       [0.54],
       [0.56],
       [0.52],
       [0.55],
       [0.61],
       [0.57],
       [0.68],
       [0.78],
       [0.94],
       [0.96],
       [0.93],
       [0.84],
       [0.74],
       [0.72],
       [0.74],
       [0.64],
       [0.44],
       [0.46],
       [0.5 ],
       [0.96],
       [0.92],
       [0.92],
       [0.94],
       [0.76],
       [0.72],
       [0.66],
       [0.64],
       [0.74],
       [0.64],
       [0.38],
       [0.34],
       [0.44],
       [0.36],
       [0.42],
       [0.48],
       [0.86],
       [0.9 ],
       [0.79],
       [0.71],
       [0.64],
       [0.62],
       [0.57],
       [0.74],
       [0.69],
       [0.87],
       [0.91],
       [0.93],
       [0.68],
       [0.61],
       [0.69],
       [0.62],
       [0.72],
       [0.59],
       [0.66],
       [0.56],
       [0.45],
       [0.47],
       [0.71],
       [0.94],
       [0.94],
       [0.57],
       [0.61],
       [0.57],
       [0.64],
       [0.85],
       [0.78],
       [0.84],
       [0.92],
       [0.96],
       [0.77],
       [0.71],
       [0.79],
       [0.89],
       [0.82],
       [0.76],
       [0.71],
       [0.8 ],
       [0.78],
       [0.84],
       [0.9 ],
       [0.92],
       [0.97],
       [0.8 ],
       [0.81],
       [0.75],
       [0.83],
       [0.96],
       [0.79],
       [0.93],
       [0.94],
       [0.86],
       [0.79],
       [0.8 ],
       [0.77],
       [0.7 ],
       [0.65],
       [0.61],
       [0.52],
       [0.57],
       [0.53],
       [0.67],
       [0.68],
       [0.81],
       [0.78],
       [0.65],
       [0.64],
       [0.64],
       [0.65],
       [0.68],
       [0.89],
       [0.86],
       [0.89],
       [0.87],
       [0.85],
       [0.9 ],
       [0.82],
       [0.72],
       [0.73],
       [0.71],
       [0.71],
       [0.68],
       [0.75],
       [0.72],
       [0.89],
       [0.84],
       [0.93],
       [0.93],
       [0.88],
       [0.9 ],
       [0.87],
       [0.86],
       [0.94],
       [0.77],
       [0.78],
       [0.73],
       [0.73],
       [0.7 ],
       [0.72],
       [0.73],
       [0.72],
       [0.97],
       [0.97],
       [0.69],
       [0.57],
       [0.63],
       [0.66],
       [0.64],
       [0.68],
       [0.79],
       [0.82],
       [0.95],
       [0.96],
       [0.94],
       [0.93],
       [0.91],
       [0.85],
       [0.84],
       [0.74],
       [0.76],
       [0.75],
       [0.76],
       [0.71],
       [0.67],
       [0.61],
       [0.63],
       [0.64],
       [0.71],
       [0.82],
       [0.73],
       [0.74],
       [0.69],
       [0.64],
       [0.91],
       [0.88],
       [0.85],
       [0.86],
       [0.7 ],
       [0.59],
       [0.6 ],
       [0.65],
       [0.7 ],
       [0.76],
       [0.63],
       [0.81],
       [0.72],
       [0.71],
       [0.8 ],
       [0.77],
       [0.74],
       [0.7 ],
       [0.71],
       [0.93],
       [0.85],
       [0.79],
       [0.76],
       [0.78],
       [0.77],
       [0.9 ],
       [0.87],
       [0.71],
       [0.7 ],
       [0.7 ],
       [0.75],
       [0.71],
       [0.72],
       [0.73],
       [0.83],
       [0.77],
       [0.72],
       [0.54],
       [0.49],
       [0.52],
       [0.58],
       [0.78],
       [0.89],
       [0.7 ],
       [0.66],
       [0.67],
       [0.68],
       [0.8 ],
       [0.81],
       [0.8 ],
       [0.94],
       [0.93],
       [0.92],
       [0.89],
       [0.82],
       [0.79],
       [0.58],
       [0.56],
       [0.56],
       [0.64],
       [0.61],
       [0.68],
       [0.76],
       [0.86],
       [0.9 ],
       [0.71],
       [0.62],
       [0.66],
       [0.65],
       [0.73],
       [0.62],
       [0.74],
       [0.79],
       [0.8 ],
       [0.69],
       [0.7 ],
       [0.76],
       [0.84],
       [0.78],
       [0.67],
       [0.66],
       [0.65],
       [0.54],
       [0.58],
       [0.79],
       [0.8 ],
       [0.75],
       [0.73],
       [0.72],
       [0.62],
       [0.67],
       [0.81],
       [0.63],
       [0.69],
       [0.8 ],
       [0.43],
       [0.8 ],
       [0.73],
       [0.75],
       [0.71],
       [0.73],
       [0.83],
       [0.72],
       [0.94],
       [0.81],
       [0.81],
       [0.75],
       [0.79],
       [0.58],
       [0.59],
       [0.47],
       [0.49],
       [0.47],
       [0.42],
       [0.57],
       [0.62],
       [0.74],
       [0.73],
       [0.64],
       [0.63],
       [0.59],
       [0.73],
       [0.79],
       [0.68],
       [0.7 ],
       [0.81],
       [0.85],
       [0.93],
       [0.91],
       [0.69],
       [0.77],
       [0.86],
       [0.74],
       [0.57],
       [0.51],
       [0.67],
       [0.72],
       [0.89],
       [0.95],
       [0.79],
       [0.39],
       [0.38],
       [0.34],
       [0.47],
       [0.56],
       [0.71],
       [0.78],
       [0.73],
       [0.82],
       [0.62],
       [0.96],
       [0.96],
       [0.46],
       [0.53],
       [0.49],
       [0.76],
       [0.64],
       [0.71],
       [0.84],
       [0.77],
       [0.89],
       [0.82],
       [0.84],
       [0.91],
       [0.67],
       [0.95]])

## Splitting the data

In [18]:
pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.5.2-cp39-cp39-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\aedur\anaconda3\envs\haritha\lib\site-packages (from scikit-learn) (1.26.4)
Collecting scipy>=1.6.0 (from scikit-learn)
  Using cached scipy-1.13.1-cp39-cp39-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.5.2-cp39-cp39-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB 1.9 MB/s eta 0:00:06
   - -------------------------------------- 0.3/11.0 MB 5.4 MB/s eta 0:00:02
   -- ------------------------------------- 0.8/11.0 MB 6.8 MB/s eta 0:00:02
   ---- ----------------------------------- 1.2/11.0 MB 7.5 MB/s eta 0:00:02
   ------ --------------------------------- 1.7/11.0 MB 8.5 MB/s eta 0:00:02
   -------- ------------------------------- 2.3/11.0 MB 9.2 MB/s eta 0:00:01
   ---------- ----------------------------- 3.0/11.0 MB 10.2 MB/s eta 0:00:01
   ------------- -------------------------- 3.7/11.0 MB 10.7 MB/s eta 0:00:01
   --------------- ------------------------ 4.4/11.0 MB 11.2 MB/s eta 0:00:01
   ------------------ --------------------- 5.1/11.0 MB 11.6 MB/s eta 0:00:01
   -------------------- ------------------- 5.7/11.0 MB 11.8 MB/s eta 0:00:01
   ---------------------- ----------------- 6.2/11.0 MB 12.0 MB/s eta 0:00:01
   ------------------------- -------------- 7.0/11.0 MB 12.0 MB/s eta 0:00:01
   --------------------------- ------------ 7.7/11.0 MB 12.3 MB/s eta 0:00:01
   ----------------------------- ---------- 8.2/11.0 MB 12.2 MB/s eta 0:00:01
   -------------------------------- ------- 8.9/11.0 MB 12.4 MB/s eta 0:00:01
   ---------------------------------- ----- 9.6/11.0 MB 12.8 MB/s eta 0:00:01
   ------------------------------------- -- 10.3/11.0 MB 13.4 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.0 MB 14.2 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.0 MB 13.9 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.0 MB 13.9 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 11.9 MB/s eta 0:00:00
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached scipy-1.13.1-cp39-cp39-win_amd64.whl (46.2 MB)
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.5.2 scipy-1.13.1 threadpoolctl-3.5.0
Note: you may need to restart the kernel to use updated packages.

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [21]:
y_test

array([[0.71],
       [0.7 ],
       [0.79],
       [0.73],
       [0.72],
       [0.48],
       [0.77],
       [0.71],
       [0.9 ],
       [0.94],
       [0.58],
       [0.89],
       [0.72],
       [0.57],
       [0.78],
       [0.42],
       [0.64],
       [0.84],
       [0.63],
       [0.72],
       [0.9 ],
       [0.83],
       [0.57],
       [0.47],
       [0.85],
       [0.67],
       [0.44],
       [0.54],
       [0.92],
       [0.62],
       [0.68],
       [0.73],
       [0.73],
       [0.61],
       [0.55],
       [0.74],
       [0.64],
       [0.89],
       [0.73],
       [0.95],
       [0.71],
       [0.72],
       [0.75],
       [0.76],
       [0.86],
       [0.7 ],
       [0.39],
       [0.79],
       [0.61],
       [0.64],
       [0.71],
       [0.8 ],
       [0.61],
       [0.89],
       [0.68],
       [0.79],
       [0.78],
       [0.52],
       [0.76],
       [0.88],
       [0.74],
       [0.49],
       [0.65],
       [0.59],
       [0.87],
       [0.89],
       [0.81],
       [0.9 ],
       [0.8 ],
       [0.76],
       [0.68],
       [0.87],
       [0.68],
       [0.64],
       [0.91],
       [0.61],
       [0.69],
       [0.62],
       [0.93],
       [0.43]])

In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
lm=LinearRegression()

In [24]:
lm.fit(x_train,y_train)

LinearRegression()

In [25]:
ypredict=lm.predict(x_test)

In [26]:
ypredict

array([[0.71526369],
       [0.72367342],
       [0.75731236],
       [0.65219067],
       [0.75100506],
       [0.61855173],
       [0.74259533],
       [0.61644929],
       [0.8834584 ],
       [0.896073  ],
       [0.55547871],
       [0.86663893],
       [0.71526369],
       [0.43984484],
       [0.82879512],
       [0.6606004 ],
       [0.6353712 ],
       [0.83930729],
       [0.57440061],
       [0.74259533],
       [0.84140972],
       [0.83720485],
       [0.69634178],
       [0.45876675],
       [0.78043914],
       [0.60593712],
       [0.50081543],
       [0.6606004 ],
       [0.84771702],
       [0.65008823],
       [0.60593712],
       [0.71316125],
       [0.73418559],
       [0.60383469],
       [0.79095131],
       [0.74890263],
       [0.58070792],
       [0.85612676],
       [0.6542931 ],
       [0.94653142],
       [0.69423935],
       [0.6542931 ],
       [0.63957607],
       [0.78043914],
       [0.83089755],
       [0.59752739],
       [0.5239422 ],
       [0.67531744],
       [0.62696146],
       [0.61224442],
       [0.69844421],
       [0.79936104],
       [0.66480527],
       [0.82248782],
       [0.73208316],
       [0.7657221 ],
       [0.59752739],
       [0.68162474],
       [0.7657221 ],
       [0.82879512],
       [0.78674644],
       [0.52183977],
       [0.6416785 ],
       [0.52814707],
       [0.80356591],
       [0.85402432],
       [0.73208316],
       [0.87925353],
       [0.78464401],
       [0.7531075 ],
       [0.57650305],
       [0.83510242],
       [0.85402432],
       [0.57650305],
       [0.90448274],
       [0.63957607],
       [0.67321501],
       [0.68793205],
       [0.92130221],
       [0.57440061]])

In [27]:
comparison=pd.DataFrame(x_test,columns=["input Data"])

In [29]:
comparison["AVL O/P"]=y_test

In [30]:
comparison

    input Data  AVL O/P
0         8.56     0.71
1         8.60     0.70
2         8.76     0.79
3         8.26     0.73
4         8.73     0.72
..         ...      ...
75        8.20     0.61
76        8.36     0.69
77        8.43     0.62
78        9.54     0.93
79        7.89     0.43

[80 rows x 2 columns]

In [31]:
comparison["Pred_O/P"]=ypredict

In [32]:
comparison

    input Data  AVL O/P  Pred_O/P
0         8.56     0.71  0.715264
1         8.60     0.70  0.723673
2         8.76     0.79  0.757312
3         8.26     0.73  0.652191
4         8.73     0.72  0.751005
..         ...      ...       ...
75        8.20     0.61  0.639576
76        8.36     0.69  0.673215
77        8.43     0.62  0.687932
78        9.54     0.93  0.921302
79        7.89     0.43  0.574401

[80 rows x 3 columns]